name: Blob storage website CI
on:
  push:
    branches:
      [ 'main' ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: 'build'
          container_name: 'alpha'
          connection_string: ${{ secrets.STFLAISCDN_CONNECTION_STRING }}
          extra_args: --destination-path ${{ github.event.repository.name }}
          overwrite: 'true'