name: Blob storage website CI
on:
  push:
    branches:
      [ 'main' ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - name: Delete static folder
#        uses: azure/CLI@v1
#        with:
#          azcliversion: 2.30.0
#          inlineScript: |
#            az storage blob delete-batch --source alpha \
#            --account-name stflaiscdn \
#            --pattern flais-cdn-test/static/css \
#            --account-key ${{ secret.STFLAISCDN_KEY }}
      - name: Azure login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az webapp list --query "[?state=='Running']"

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: 'build'
          container_name: 'alpha'
          connection_string: ${{ secrets.STFLAISCDN_CONNECTION_STRING }}
          extra_args: --destination-path ${{ github.event.repository.name }}
          overwrite: 'true'